// front-angular/src/app/views/home/home.component.ts
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {

 @Input() msg: string;
 legenda: string = 'Estou no Angular';
 
  constructor() { }

  ngOnInit(): void {
  }

  resetLegenda() :void {
    this.legenda = 'Estou no Angular';
  }

}

<h1>{{ msg }}</h1>
<h2>{{ legenda }}</h2>
<input  type="text"  [(ngModel)]="legenda" />

<button (click)="resetLegenda()">Reset Legenda</button>

// front-react/src/views/home/Home.js
import React, { useState } from 'react';

import './Home.css';
export default (props) => {
   let [legenda, setLegenda] = useState('Estou no React');

   function resetLegenda() {
      setLegenda('Estou no React')
   }

   return (
      <div className="home">
           <h1>{ props.msg }</h1>
           <h2>{ legenda }</h2>
           <input  value={legenda} onChange={ e=> setLegenda(e.target.value) } />
           <button onClick={ resetLegenda }>Reset Legenda</button>
      </div>
   );
}
